In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
print(np.__version__)

1.16.1


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
arr1 = np.array(20)
print(arr1)

20


In [12]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[10,11,12],[13,14,15]]])
print(arr3)

[[list([1, 2, 3, 4]) list([5, 6, 7, 8])]
 [list([10, 11, 12]) list([13, 14, 15])]]


In [16]:
#checking number of dimensions
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
0
2
2


In [18]:
arr4 =np.array([1,2,3,4],ndmin=5)
print(arr4)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
1


In [19]:
print(arr[2])

3


In [20]:
print(arr2[0])

[1 2 3 4]


In [26]:
print(arr2[1][0])

5


In [28]:
print(arr2[0][1] + arr2[1][0])

7


In [40]:
a = np.array([1,2,3,4,5,6,7,8])
print(a[3:])
print(a[:3])
print(a[:])
print(a[-2:])
print(a[-3:-1])
print(a[2:5])
print(a[1:5:2])

[4 5 6 7 8]
[1 2 3]
[1 2 3 4 5 6 7 8]
[7 8]
[6 7]
[3 4 5]
[2 4]


In [43]:
import pandas as pd
data = np.array([['','Col1','Col2'],
                ['Row1',1,2],
                ['Row2',3,4]])
                
print(pd.DataFrame(data=data[1:,1:],index=data[1:,0],columns=data[0,1:]))

     Col1 Col2
Row1    1    2
Row2    3    4


In [44]:
# creating the Numpy array 
array = np.array([[1, 1, 1], [2, 4, 8], [3, 9, 27],  
                  [4, 16, 64], [5, 25, 125], [6, 36, 216],  
                  [7, 49, 343]]) 
  
# creating a list of index names 
index_values = ['first', 'second', 'third', 
                'fourth', 'fifth', 'sixth', 'seventh'] 
   
# creating a list of column names 
column_values = ['number', 'squares', 'cubes'] 
  
# creating the dataframe 
df = pd.DataFrame(data = array,  
                  index = index_values,  
                  columns = column_values) 
  
# displaying the dataframe 
print(df) 

         number  squares  cubes
first         1        1      1
second        2        4      8
third         3        9     27
fourth        4       16     64
fifth         5       25    125
sixth         6       36    216
seventh       7       49    343
